version: '3.3'

services:
  server:
    build: ./server
    ports:
      - '5000:5000'
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_USER: 'ivs'
    volumes:
      - data:/var/lib/postgresql/data
  
volumes:
  data: